### ISSUE TITLE
Possible integration of stabilizer

### ISSUE THREAD

**Issue by smr97** [rust-lang/measureme#115]
Hi,
I came across a very interesting talk by Prof Emery Berger on how the placement of functions in assembly and even the choice of memory layout might influence the time measurements. I have been benchmarking some parallel sorts using criterion as of now. I do see up to 50-70ms difference (on a scale of 300ms) in the wall-time of the exact same code when I have different set of benchmarking functions in the same group with it.

I would be very interested in a time-measurement crate that would randomize the instructions layout and the memory layout of objects. Here is a link to the project that does this for C/C++ (as mentioned in the talk) https://github.com/ccurtsinger/stabilizer.

Also, some quick thoughts on possible implementations would be helpful.

**Comment by bjorn3** [comment]
It should be possible to run stabilizer on a program and then merge the resulting measureme profiles. There is no program to do this yet though.

**Comment by bjorn3** [comment]
Measureme is for more high-level profiling. In your case the profiling itself is likely to influence the profile results significantly. You will have better luck with a statistical profiler like `perf`. For `perf` you could easily run stabilizer and then merge the profiles by simply concatenating the `perf script` outputs for each run before passing it to for example `flamegraph.pl`.

**Comment by smr97** [comment]
I see, I agree with you on the profiler front. I am talking about the use-case of benchmarking only.
Now, I'm confused about running stabilizer on a program. Could you please explain with an example how that could work? With the readme in the link I posted, I see that the stabilizer works on the source code, and not on an executable (I guess because if the machine code is generated, then it is already too late to randomize layout).

Thanks for the patience!

**Comment by bjorn3** [comment]
I assumed that it would work on the final executable. However according to the readme, stabilizer is implemented as pass for an ancient version of LLVM. The driver also only works for gcc (with the dragonegg plugin to translate to LLVM) and clang.

**Comment by smr97** [comment]
I see, yeah I was quite certain there is not an easy workaround to this. If you think that this is outside the scope of this repository, please feel free to close the issue.

Thanks

**Comment by wesleywiser** [comment]
It seems like a cool idea @smr97! I think this is pretty far outside the scope of this project though which is focused primary on source-based tracing annotations.
