### ISSUE TITLE
Cut new releases?

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/measureme#126]
measureme itself is at 0.7.1, an entirely respectable version number. However, recent commits have grown its capabilities and updated its dependencies. It's been a while, so it should probably get to grow up to be 0.7.2 or 0.8.0, along with some of the other workspace members.

**Comment by wesleywiser** [comment]
Yeah definitely! I believe there are some breaking changes coming in a bit but we can do a point release now.

**Comment by wesleywiser** [comment]
We also should update https://blog.rust-lang.org/inside-rust/2020/02/25/intro-rustc-self-profile.html so that it's consistent with the new measuring format.

**Comment by wesleywiser** [comment]
We cut a new release and https://github.com/rust-lang/rust/pull/77398 landed so we can close this.
