### ISSUE TITLE
Could not find .mm_profdata file

### ISSUE THREAD

**Issue by fpoli** [rust-lang/measureme#135]
I'm using for the first time `measureme` to profile the compilation time of a project which needs to be compiled with `nightly-2020-09-30`. I followed [this guide](https://github.com/rust-lang/measureme/blob/master/crox/Readme.md) and I'm getting the following error.

```
Error: "Could not find profiling data file `prusti_driver-32670.mm_profdata`.It looks like your profiling data has been generated by an out-dated version of measureme (0.7 or older)."
```

Is it because the `measureme` version that comes with `nightly-2020-09-30` is out-dated? Do you know any workarounds?

**Comment by fpoli** [comment]
To match the version used by rustc I had to run `cargo install` with a tag:
```
cargo install --git https://github.com/rust-lang/measureme --tag 0.7.1 crox flamegraph summarize
```
Maybe it's worth adding this to the guide, mentioning that it also depends on the version of rustc.

**Comment by kennykerr** [comment]
I ran into the same problem after following the instructions here:

https://blog.rust-lang.org/inside-rust/2020/02/25/intro-rustc-self-profile.html

Thanks for the tip!

**Comment by wesleywiser** [comment]
Just FYI, this is happening because we've made some breaking changes to this crate but rustc hasn't been updated yet to the latest version. We're getting ready to do that now so this should be resolved in the next week hopefully.

**Comment by wesleywiser** [comment]
Since https://github.com/rust-lang/rust/pull/77398 landed yesterday, this should be resolved.
