### ISSUE TITLE
called unwrap() on None

### ISSUE THREAD

**Issue by jyn514** [rust-lang/measureme#149]
```
$ summarize summarize stm32h7xx_hal-21900.mm_profdata 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', analyzeme/src/profiling_data.rs:58:71
```

<details>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', analyzeme/src/profiling_data.rs:58:71
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d78d1d02761b906038ba4d54c5f3427f920f5fb/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/9d78d1d02761b906038ba4d54c5f3427f920f5fb/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9d78d1d02761b906038ba4d54c5f3427f920f5fb/library/core/src/panicking.rs:50:5
   3: analyzeme::profiling_data::ProfilingData::new
   4: summarize::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

https://github.com/rust-lang/measureme/blob/16688a5da98f403b2b7f1942564adf3361c99cff/analyzeme/src/profiling_data.rs#L58

I guess the generated file is invalid? Not sure why that would happen, it didn't spit any errors at me.

**Comment by jyn514** [comment]
FWIW I generated this with `command time -v cargo rustdoc --features=stm32h743v,rt,quadspi,sdmmc,fmc,rtc,ethernet -- -Z self-profile` on https://github.com/stm32-rs/stm32h7xx-hal.

**Comment by andjo403** [comment]
I can not reproduce this with any combination of:
rustc 1.52.0-nightly (8e54a2113 2021-02-13)
rustc 1.50.0-nightly (f76ecd066 2020-12-15)
from https://github.com/stm32-rs/stm32h7xx-hal:
7d81332985f23c4456dc3059cc986092cc63d12e (master 14 feb)
848329426b14309e3cb6acefde9f8182c1e356ed master(16 dec)

@jyn514  do you know if you have hade this fault more times? or what versions that you was using

**Comment by jyn514** [comment]
I haven't run into this in a while and don't know how to reproduce it.
