### ISSUE TITLE
Store some metadata about the profile in a reserved string table slot.

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/measureme#15]
It might be useful to store data about a collected profile with the profile itself (like process-id, start-time). It occurred to me that we could just pack this data into a JSON string and store that under a pre-reserved `StringId` in the string table. Then we don't need to implement this in the more cumbersome binary format. 

cc @wesleywiser

**Comment by wesleywiser** [comment]
After we've added the reserved string, we should also modify the [`Event`](https://github.com/rust-lang/measureme/blob/582b99b5c6c03411076a3c8950630fff380a799a/measureme/src/event.rs) struct to include this data. Then make the [events iterator](https://github.com/rust-lang/measureme/blob/582b99b5c6c03411076a3c8950630fff380a799a/measureme/src/profiling_data.rs#L31) fetch that data once and include it with each returned `Event`.

**Comment by michaelwoerister** [comment]
Steps to implement this:
- Add a reserved string table id `METADATA_STRING_ID` to `stringtable.rs` and make sure it does not clash with other string table IDs:
https://github.com/rust-lang/measureme/blob/582b99b5c6c03411076a3c8950630fff380a799a/measureme/src/stringtable.rs#L48
- Update [Profiler::new](https://github.com/rust-lang/measureme/blob/bb145450bbb3d66caf788429bf7d4de907431209/measureme/src/profiler.rs#L33-L50) to store a JSON object with the following data in the stringtable:
  - The `start_time` as nano seconds since [UNIX_EPOCH](https://doc.rust-lang.org/std/time/constant.UNIX_EPOCH.html)
  - The process id as given by `std::process::id()`
  - The command line, as inferred from the functions available in `std::env`

**Comment by michaelwoerister** [comment]
Some more notes:
- Generating the JSON object string should be simple enough as not to require pulling in a dependency like serde.
- It should be OK to use `std::env::args_os()` and then `OsString::to_string_lossy()` in order to reliably convert the command line into UTF-8.

**Comment by Mark-Simulacrum** [comment]
> Generating the JSON object string should be simple enough as not to require pulling in a dependency like serde.

I personally think we should just do it -- serde is already a dependency for most crates and historically generating JSON without something like it doesn't go well (we've had bugs with malformed JSON). We could also go for https://github.com/dtolnay/miniserde as a way of skipping the costs involved with Serde.

**Comment by amanjeev** [comment]
Just checking if anyone is actively working on this issue. Anyone?

**Comment by michaelwoerister** [comment]
The `measureme` crate is what gets included into other projects. I think it should stay lightweight. It's a single `format!()` we are not talking about here. Using `serde` for that is actually a lot more complicated, if you ask me.

**Comment by Mark-Simulacrum** [comment]
Hm, perhaps -- I basically only want Serde or something like it to confirm we're actually producing valid JSON, so we could make it a dev-dep and test -- or just rely on manual testing for now.

**Comment by wesleywiser** [comment]
I think we should have a few tests around this feature that set up some state, record the JSON data and then verify the string is exactly what we expect it to be. In the past, we had issues with the JSON encoding because 1) I'm bad at JSON 2) the long build-test cycle time in rustc made it hard to manually test a lot of changes. Having a couple tests for this should resolve both of those issues.

**Comment by amanjeev** [comment]
What's the verdict for serde/miniserde?

**Comment by wesleywiser** [comment]
In terms of recording the JSON data in `measureme`, I don't think we should use serde/miniserde at this time. However, I don't see any reason why we couldn't use it for the binary tools in this repro (ie, `summarize`, `stack-collapse`, etc).
