### ISSUE TITLE
RUSTSEC-2020-0077: memmap is unmaintained

### ISSUE THREAD

**Issue by SamuelQZQ** [rust-lang/measureme#153]
The `memmap` is unmaintained. Maybe we should replace it with `memmap2`?

**Comment by SamuelQZQ** [comment]
@wesleywiser Maybe a stupid question, how can I know when will the new release including this change available?

**Comment by wesleywiser** [comment]
@SamuelQZQ not a stupid question at all! Thanks for the ping, I've just released `9.1.1` which has this change included.
