### ISSUE TITLE
compile error while attempting to install measureme on current nightly

### ISSUE THREAD

**Issue by elidupree** [rust-lang/measureme#167]
I tried to run: `cargo install --git https://github.com/rust-lang/measureme crox flamegraph summarize`
On rustc version: `rustc 1.55.0-nightly (798baebde 2021-07-02)`
And got (three copies of) this error:
```
error: unused borrow that must be used
   --> measureme\src\stringtable.rs:189:17
    |
189 |                 &mut bytes[1..5].copy_from_slice(&string_id.0.to_le_bytes());
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> measureme\src\lib.rs:36:9
    |
36  | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(unused_must_use)]` implied by `#[deny(warnings)]`
```

The message seems to be warning about something that is indeed questionable - it looks like [the offending line](https://github.com/rust-lang/measureme/blob/d5050c08811d796fd8f4cc42da895a8468ae5f78/measureme/src/stringtable.rs#L189) could have the &mut removed without changing its behavior, making it similar to the line in the other branch.

**Comment by Mark-Simulacrum** [comment]
Filed https://github.com/rust-lang/measureme/pull/168 with a fix.
