### ISSUE TITLE
Release to crates.io

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/measureme#20]
@michaelwoerister unless you have any objections, after #18 and #19 merge, I'd like to release a version to crates.io so we can get https://github.com/rust-lang/rust/pull/59515 merged. 

This issue tracks the release on crates.io.

I propose that we use pre-release versions when uploading to crates.io as we don't have any stability guarantees at this point. Therefore, the first release will be `0.1.0` and the next release will be `0.2.0`, etc.

**Comment by michaelwoerister** [comment]
I have no objections `:)` 

I think going with `0.x` versions for now is reasonable.

**Comment by wesleywiser** [comment]
Actually, I forgot we published an empty `0.1.0` crate to reserve the name on crates.io. So this will actually be `0.2.0` (see #21)

**Comment by wesleywiser** [comment]
We're live now https://crates.io/crates/measureme
