### ISSUE TITLE
`summarize` segfaults on large .mm_profdata files

### ISSUE THREAD

**Issue by jyn514** [rust-lang/measureme#201]
```
$ summarize summarize rustc_query_impl-0451821.mm_profdata 
Segmentation fault (core dumped)
(gdb) where
#0  0x000055555560a830 in prettytable::TableSlice::get_all_column_width ()
#1  0x000055555560ac6c in prettytable::TableSlice::print_tty ()
#2  0x0000555555596eae in summarize::main ()
#3  0x0000555555585e73 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#4  0x00005555555a9549 in _ZN3std2rt10lang_start28_$u7b$$u7b$closure$u7d$$u7d$17h8cd4f4bd161a785dE.llvm.11794847080403208026 ()
```
This is because of https://github.com/phsym/prettytable-rs/pull/146, I switched measureme to use that fork locally and it fixed the issue.

**Comment by jyn514** [comment]
We might also want to consider switching to a new library if that PR doesn't get merged reasonably soon; https://crates.io/crates/tabled looks reasonable.

**Comment by pinkforest** [comment]
PR's up #202 with the fix in-release

**Comment by jyn514** [comment]
Thank you! I didn't expect you to reply to soon, I really appreciate it ❤️
