### ISSUE TITLE
Job 1, `summarize summarize test.mm_profdata` terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by avdb13** [rust-lang/measureme#204]
I'm getting the following error when trying to inspect the generated `mm_profdata` file.
Here is the file for a reference: https://files.catbox.moe/u3zfr1.mm_profdata

**Comment by bjorn3** [comment]
Try installing from the master branch. There was a dependency which did something unsound. This dependency has been updated in https://github.com/rust-lang/measureme/pull/202.
