### ISSUE TITLE
I'm not getting profile data

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/measureme#235]
I'm not sure what I'm doing wrong.
1. `cargo clean`
2.`RUSTFLAGS="-Zself-profile" cargo +nightly build`
3. it only creates two files:
  ___-0213414.mm_profdata
 ___-0213417.mm_profdata
  which on `summarize summarize` only contain this:
  ```
+---------------+-----------+-----------------+---------+------------+
| Item          | Self time | % of total time | Time    | Item count |
+---------------+-----------+-----------------+---------+------------+
| drop_compiler | 46.24µs   | 100.000         | 46.24µs | 1          |
+---------------+-----------+-----------------+---------+------------+
Total cpu time: 46.241µs
+------+---------------+
| Item | Artifact Size |
+------+---------------+
```

The crate has no issues and builds and tests fine, though.
There's nothing weird in the manifest

**Comment by bjorn3** [comment]
Try `RUSTFLAGS="-Zself-profile=$(pwd)" cargo +nightly build` to put all profiles in the current working directory. By default it is put in the working directory of the rustc instance I believe, which for dependencies from crates.io is the source dir of these crates as opposed to the source dir of your project.

**Comment by dev-ardi** [comment]
Is there a way to put all in a subdir of the cwd? Or even better, sum all of them

**Comment by bjorn3** [comment]
> Is there a way to put all in a subdir of the cwd?

You can use `RUSTFLAGS="-Zself-profile=$(pwd)/subdir" cargo +nightly build`.

> Or even better, sum all of them

There is no way to build a single combined profile. If you want a combined flamegraph you could run `stack_collapse` on each profile individually and then append the output of all invocations and pipe it through eg the original flamegraph.pl (https://github.com/brendangregg/FlameGraph) to get an svg. Or you could load it in <https://speedscope.app>.

**Comment by dev-ardi** [comment]
Thank you!
