### ISSUE TITLE
Failed to build target `x86_64-unknown-linux-ohos` for crate

### ISSUE THREAD

**Issue by LuuuXXX** [rust-lang/measureme#237]
Recently, I tried to build target `x86_64-unknown-linux-ohos`, and conditionally compiled `perf-event-open-sys` in the dependency. 
![Image](https://github.com/user-attachments/assets/e32df778-5182-4f9d-b9e9-8f92d5543662)

Here's an error report.
![Image](https://github.com/user-attachments/assets/09103bca-6f4f-4b3f-ad84-b36b14995207)

 I'd like to consult if this dependency is necessary, it seems to have been archived.
.

**Comment by saethlin** [comment]
Per the diagnostic, this is a bug in `perf-event-open-sys`, or perhaps something even farther upstream than that.

**Comment by LuuuXXX** [comment]
> Per the diagnostic, this is a bug in perf-event-open-sys

It seems perf-event-open-sys has been archived, perf-event hasn't been updated for a long time, may I replace it with perf-event-open-sys2.
