### ISSUE TITLE
Filter out small items from summarize table

### ISSUE THREAD

**Issue by Darksonn** [rust-lang/measureme#32]
Since the table printed by summarize is intended to be read by humans, we should avoid printing every simple item, since it results in many lines of output (1000 lines for the regex crate).

I propose to provide a parameter to filter lines, so only those items worth more than some percentage of the total runtime are shown. (or similar)

As for choosing a default value, one should probably experiment a bit to figure out where the long tail is. For reference the items with runtime > 1% are 76% of the total runtime on the regex crate.

**Comment by amanjeev** [comment]
I will take a shot at this.
