### ISSUE TITLE
Is this link broken?

### ISSUE THREAD

**Issue by dorayakikun** [rust-lang/measureme#53]
The below link seems to broken.

https://github.com/rust-lang/measureme/blame/34792560521a30030b2949b2c9dce881dea77852/README.md#L8

Is this link intended?
https://rust-lang.github.io/compiler-team/working-groups/self-profile/

If the above is correct, will open pull request.

**Comment by wesleywiser** [comment]
Yep! That's correct.

**Comment by dorayakikun** [comment]
Thank you for your reply.
I'll open a  Pull Request!
