### ISSUE TITLE
Panic in summarize

### ISSUE THREAD

**Issue by lnicola** [rust-lang/measureme#66]
```
$ cargo new hello
$ cd hello
$ RUSTFLAGS=-Zself-profile cargo build
$ ~/measureme/target/release/summarize summarize hello-750698
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"codegen_and_optimize_crate"`,
 right: `"codegen_crate"`', summarize/src/analysis.rs:121:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by andjo403** [comment]
think that this have already been fixed https://github.com/rust-lang/rust/pull/65137 what version of rustc are you using?

**Comment by wesleywiser** [comment]
https://github.com/rust-lang/rust/pull/65137 landed 3 days ago so you probably need a nightly from the last two days to get that fix.

**Comment by lnicola** [comment]
Good point, sorry. I'll try to update.

**Comment by wesleywiser** [comment]
No worries! Let us know if you're still seeing the issue 🙂
