### ISSUE TITLE
Tools should use FxHashMap instead sip-hash based hash maps or BTreeMaps

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/measureme#77]
`FxHashMap` from `rustc-hash` is fast and we are doing lots of hashing.

**Comment by silathdiir** [comment]
Hello, I'm interested in working on this issue.

@michaelwoerister , I did a search on the source code. Should I replace all calling `std::collections::HashMap` and `std::collections::BTreeMap` with `FxHashMap`?

Please correct me if I was wrong. Thank you.

**Comment by michaelwoerister** [comment]
Yes, I think all HashMaps and BTreeMaps can be replaced with FxHashMap. It would be good to wait until https://github.com/rust-lang/measureme/pull/76 has landed though, as that PR changes a lot of code.

**Comment by silathdiir** [comment]
Got it. Thank you. I will move on until #76 is merged.

**Comment by michaelwoerister** [comment]
#76 has just been merged.

**Comment by silathdiir** [comment]
Hi @michaelwoerister , I tries to fix this on PR #82 . Please help review it.

And I am sorry that I could not find the corresponding method `HashMap::with_capacity` in FxHashMap (and FxHashSet).
I used `FxHashMap::default` directly. I could not confirm if it is right. Please correct me if i was wrong.

**Comment by silathdiir** [comment]
Based on @michaelwoerister 's help, I fixed to replace `HashMap::with_capacity` with `FxHashMap::with_capacity_and_hasher`. Thanks.

**Comment by michaelwoerister** [comment]
Closing. Implemented in #82.
