### ISSUE TITLE
"summarize diff" could show relative statistic numbers

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/measureme#81]
I was [looking at the output of `summarize diff`](https://gist.github.com/alexcrichton/03306558740b8f4363a18482e0653cc5) recently and was able to get some useful information (wow was LLVM a lot slower!). I think it'd be useful to also have information, though, for things like "how much slower" or "how much faster" are the two builds. For example it'd be cool to have an inline statistic saying like "LLVM is 100% slower" or "`is_copy_raw` is 10% slower". The absolute times are great but having relative times can also be good for putting things in context!

**Comment by andjo403** [comment]
@alexcrichton is it an per item relative number that you think of or is it how mush this item have contributed to the total time change?
e.g. maybe not that interesting to see that is_copy_raw is 3ms slower when the build is 11s slower and LLVM_thin_lto_optimize is 3s slower.

**Comment by alexcrichton** [comment]
Yeah I think per-item would be ideal, for example 100ms to 3100ms is crazy huge while 0.1ms to 3ms is miniscule
