### ISSUE TITLE
summarize: Error: "Event stream file format version \'0\' is not supported by this version of `measureme`."

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [rust-lang/measureme#94]
With latest nightly and measureme master, I get :
Error: "Event stream file format version \'0\' is not supported\n                 by this version of `measureme`."

**Comment by andjo403** [comment]
there is a fix on it's way in rustc but it have not been merged yet https://github.com/rust-lang/rust/pull/66981
you can checkout https://github.com/rust-lang/measureme/commit/3b7c3a81e04319a84edfad9e540faec843c4f603 if you do not want to wait for the rustc PR getting merged.

**Comment by michaelwoerister** [comment]
`rustc` as of https://github.com/rust-lang/rust/pull/66981 and the current `master` version of `summarize` should work together.

**Comment by wesleywiser** [comment]
rust-lang/rust#66981 has merged
